### ISSUE TITLE
KeychainSettings.Factory 

### ISSUE THREAD

**Issue by vanniktech** [russhwolf/multiplatform-settings#100]
Is there any reason that `KeychainSettings` does not come by default with a `Factory`?

Currently, I'm doing this:

```kotlin
object KeychainSettingsFactory : Settings.Factory {
  @OptIn(ExperimentalSettingsImplementation::class)
  override fun create(name: String?) = when {
    name == null -> KeychainSettings()
    else -> KeychainSettings(name)
  }
}
```

Is there anything wrong with doing that?

**Comment by russhwolf** [comment]
It should work fine. I've been reluctant to add more factory implementations because I'd like to rethink initialization in general and it's relatively easy to roll your own in the meantime.

**Comment by vanniktech** [comment]
Alright, good to know.

Personally, I'm a huge fan of having a Settings.Factory that's being passed down into KMP code from which I can create multiple settings. (Some device scoped, some user scoped)

**Comment by russhwolf** [comment]
At this point I'm not going to make any changes to the `Factory` interface ahead of 1.0, so I added a `KeychainSettings.Factory` in `1.0.0-alpha01`.
