### ISSUE TITLE
[Feature Request] JVM (Desktop) support for DataStore settings.

### ISSUE THREAD

**Issue by darvld** [russhwolf/multiplatform-settings#103]
The core Jetpack DataStore library does not require Android to function, this allows to use DataStore with kotlinx-serialization on pure JVM projects. Providing the JVM platform on this project's DataStore-based implementation would allow to use it on Compose Desktop and other projects.

**Comment by russhwolf** [comment]
I started laughing when I realized this triggers the exact scenario I didn't think was likely [here](https://github.com/russhwolf/multiplatform-settings/pull/97#issuecomment-925466941).

Code-wise this is straightforward, but [KT-42466](https://youtrack.jetbrains.com/issue/KT-42466) breaks some IDE support. That can be worked around, though, so I should be able to get this out at some point soon.

**Comment by russhwolf** [comment]
This has been released in version 0.9

**Comment by darvld** [comment]
Be aware, I've recently found that DataStore does not work on Windows. This is caused by the implementation of the `rename` method on the JVM, which on Windows will throw an exception if the target name represents an existing file (no option to overwrite). Unfortunately, the DataStore team seems to have no interest in resolving this issue any time soon.
