### ISSUE TITLE
Migrate to Gradle 4.10

### ISSUE THREAD

**Issue by brettwillis** [russhwolf/multiplatform-settings#11]
Many Kotlin multiplatform libraries (coroutines, serialization, atomicfu) are migrating to Gradle 4.10 (so that projects can use Android plugin 3.3.

I think your library cannot be resolved by Gradle 4.10 due to GRADLE_METADATA version 0.4 incompatible with 0.3.

Please update to publish with Gradle 4.10 and metadata 0.4.
See https://github.com/Kotlin/kotlinx.coroutines/issues/564

**Comment by russhwolf** [comment]
Fixed in v0.2
