### ISSUE TITLE
How do we inject ObservableSettings in windows?

### ISSUE THREAD

**Issue by carvalho2707** [russhwolf/multiplatform-settings#118]
My project is for windows but I can't find an example of a working ObservableSettings provided with koin/dagger.
I can only provide Settings.

Does anyone know?

**Comment by russhwolf** [comment]
It's not currently supported. The reason that `ObservableSettings` exists as a separate interface than `Settings` is that not all implementations are observable. Issue #51 already exists to track adding support on Windows.
