### ISSUE TITLE
Add a generic listener

### ISSUE THREAD

**Issue by duanemalcolm** [russhwolf/multiplatform-settings#123]
Is it possible to have a generic listener for any key change. For example,
```
settings.addListener() { key -> ... }
```
or
```
settings.addStringListener() { key, stringValue -> ... }
```
For my use case, I have a number of settings for units, e.g., precipitation, temperature and pressure. These keys for these settings are prefixed with `units_*`. By having a generic listener, I can filter these keys and only have one `unitsListener`. Currently, I have many listeners, one for each unit setting. For example,
```
settings.addStringListener() { key, value ->
   if (key.startsWith("units_") {
      updateUnitsWithValue(key, value)
   }
}
```

**Comment by russhwolf** [comment]
Unfortunately, when we don't know the key in advance, we don't always have a way to implement this API. For example with `NSUserDefaults`, we don't receive any information about what key changed when we get an update notification.

**Comment by duanemalcolm** [comment]
Ahh, yes, I was only looking at the `SharedPreferences.OnSharedPreferenceChangeListener` which provide the key. I didn't look at the Apple equivalent which doesn't have the key. Thanks. I'll close this issue.
