### ISSUE TITLE
Is it possible to support Keychain Access Groups?

### ISSUE THREAD

**Issue by jsm174** [russhwolf/multiplatform-settings#132]
Thanks for this fantastic library!

I would like to share my keychain across app extensions.

I was looking at https://github.com/russhwolf/multiplatform-settings/blob/5b478eb958552a42937e37257ed3a513190449b5/multiplatform-settings/src/appleMain/kotlin/com/russhwolf/settings/KeychainSettings.kt#L97 

and didn't see any references to `kSecAttrAccessGroup`.

Is this on the roadmap?

**Comment by russhwolf** [comment]
Does it work if you use the primary constructor instead?
```kotlin
val settings = KeychainSettings(
    kSecAttrAccessGroup to CFBridgingRetain(groupName)
)
```

**Comment by jsm174** [comment]
Hello! I apologize for taking so long to get back on this. I'm new to kotlin, so I didn't realize there was another constructor available. 

It works perfectly!

 return KeychainSettings(
            kSecAttrService to CFBridgingRetain(Constants.IOS_KEYCHAIN_SERVICE),
            kSecAttrAccessGroup to CFBridgingRetain(Constants.IOS_KEYCHAIN_GROUP),
        )
