### ISSUE TITLE
iOS/Android KMM app write data from shared code, and read from iOS Keychain and encrypted Android version

### ISSUE THREAD

**Issue by zbencz3** [russhwolf/multiplatform-settings#133]
Thanks for this awesome library @russhwolf ! I am a newbie to Android/Kotlin/KMM so please forgive me if this is something elementary. 

My goal: write sensitive data like access token using the shared code into a shared/encrypted setting, and read it from the clients iOS and Android.

So on iOS I want to consume it through the keychain services e.g. 
`EncryptedSettingsRepository(settings: KeychainSettings(service: "com.myapp"))`.
How would I go about writing data/string from the shared code? 
The default constructor `Settings()` would write into the the user defaults on iOS, not the keychain.
`private val encryptedPreferences: Settings = Settings()`

How can I pull data out in the Android app where the data comes from wherever the KeyChain data is written to? (is that encrypted)

Thanks.

**Comment by russhwolf** [comment]
You'll need to use some form of dependency injection rather than using the no-arg constructor. For example

in common code:
```kotlin
class SomeClassThatNeedsSettings(val settings: Settings) { ... }
```

in iOS code:
```kotlin
val settings - KeychainSettings(...)
val someClassThatNeedsSettings = SomeClassThatNeedsSettings(settings)
```

in Android code, if you want encryption use the [`androidx.security-crypto`](https://developer.android.com/jetpack/androidx/releases/security) lib:
```kotlin
val prefs: SharedPreferences = EncryptedSharedPreferences.create(...)
val settings = SharedPreferencesSettings(prefs)
val someClassThatNeedsSettings = SomeClassThatNeedsSettings(settings)
```

**Comment by zbencz3** [comment]
Thanks @russhwolf !
