### ISSUE TITLE
JVMSettings unable to store long value

### ISSUE THREAD

**Issue by Pschsch** [russhwolf/multiplatform-settings#134]
Seems that's due to limitation of java.util.prefs.Preferences.MAX_VALUE_LENGTH
Related answer on SO: https://stackoverflow.com/questions/27558399/preferences-in-java

**Comment by russhwolf** [comment]
Multiplatform Settings doesn't currently do anything to save you from limitations of the underlying storage mechanism. Are you looking for a workaround or just reporting that it happens?

**Comment by Pschsch** [comment]
I've made a quick workaround, because the use case in so specific. Example:
`internal fun Settings.getLongStringOrNull(key : String, partsCount : Int): String? {
    val keys = (0 until partsCount).map {
        "$key.$it"
    }
    val values = keys.mapNotNull {
        getStringOrNull(it)
    }
    if (values.isEmpty()) return null
    return values.joinToString("")
}

internal fun Settings.putLongString(key: String, value : String, partsCount: Int) {
    val keys = (0 until partsCount).map {
        "$key.$it"
    }
    val values = value.limit(8000, partsCount)
    keys.forEachIndexed { index, k ->
        putString(k, values[index])
    }
}`
But at first, I've just want to report that. Maybe, you'll want to save others from underlying storage limitations

**Comment by Pschsch** [comment]
`
internal fun Settings.getLongStringOrNull(key : String, partsCount : Int): String? {
`

**Comment by russhwolf** [comment]
Closing as I don't plan to do anything about this at the moment
