### ISSUE TITLE
Remove by key multiplatform-settings-serialization

### ISSUE THREAD

**Issue by blyscuit** [russhwolf/multiplatform-settings#136]
`multiplatform-settings-serialization` saves value by `combining the key parameter with the property name.` and not possible to remove the values by sending key and value type. 

Add support for, would be really appreciated.
```
settings.remove(
    serializer: KSerializer<T>,
    key: String
)
```
Currently I'm using this as a a workaround
```
    override fun remove(key: String) {
        settings
            .keys
            .filter { it.startsWith(key) }
            .map { settings.remove(it) }
    }
```

**Comment by russhwolf** [comment]
This is already being tracked in #81 and there's a draft implementation in #117
