### ISSUE TITLE
iOS build getting failed after adding dependency

### ISSUE THREAD

**Issue by manishktx** [russhwolf/multiplatform-settings#145]
After adding dependency "com.russhwolf:multiplatform-settings-no-arg:1.0.0" android build runs fine but iOS build is getting failed due to "shared" module's classes are not found in iOS-app codebase. If I remove the dependency everything runs fine. 

Using kotlin version: 1.7.21
POD file 
target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'GoogleMaps', '7.2.0' 
end

**Comment by russhwolf** [comment]
Version 1.0.0 of the library was built with Kotlin 1.8, so it might not work from Kotlin 1.7.20. Try upgrading your Kotlin version, or if you can't, you might be able to use 1.0.0-RC instead.

**Comment by manishktx** [comment]
Thanks @russhwolf  it is solved now.
