### ISSUE TITLE
Unresolved reference: JsSettings after update to 1.0.0

### ISSUE THREAD

**Issue by sebleclerc** [russhwolf/multiplatform-settings#146]
I have a KotlinJS / Compose for Web module which I just updated from Multiplatform settings 0.9 to 1.0.0
Since then, I have that unresolved reference error.
This is (part of) my build.gradle file:
```
kotlin {
  js(IR) {
    browser()
    binaries.executable()
  }

  sourceSets {
    val jsMain by getting {
      dependencies {
        [...]

        implementation(Deps.multiplatformSettings)
      }
    }

    val jsTest by getting
  }
}
```
And then I init it this way:
```
private val settings: Settings = JsSettings()
```

It was part of a broader dependency updates but only rolling back to version 0.9 fixed that.

**Comment by russhwolf** [comment]
`JsSettings` has been renamed `StorageSettings`. There were a number of breaking changes in 1.0.0 as described in the [changelog](https://github.com/russhwolf/multiplatform-settings/blob/main/CHANGELOG.md#v100-alpha01-2022-06-02)

**Comment by russhwolf** [comment]
Oh sorry. I accidentally left that out and didn't notice.

**Comment by sebleclerc** [comment]
No worries! I got it all settled so it's all good! 😄
