### ISSUE TITLE
Provide API for serialized value removal

### ISSUE THREAD

**Issue by MJegorovas** [russhwolf/multiplatform-settings#148]
Would be nice to have an API that could be used to easily remove serialized value from settings. Current `remove` does not work, because settings keys are actually a combination of key and property name. Working around this at the moment with this:
```val key = "key"
for (settingsKey in settings.keys) {
    if (settingsKey.startsWith(key)) settings.remove(settingsKey)
}

**Comment by russhwolf** [comment]
Closing as a dupe of #81.
