### ISSUE TITLE
Javascript platform

### ISSUE THREAD

**Issue by galex** [russhwolf/multiplatform-settings#15]
I'd like to use this in an mpp project which contains a Javascript module as well. 
Do you have an idea how to implement the js platform?

Regards,
Alex

**Comment by russhwolf** [comment]
I opened #12 to get user input on other expanding the library to other platforms. One possibility I've identified is using the [storage](https://kotlinlang.org/api/latest/jvm/stdlib/org.w3c.dom/-storage/index.html) api. I've done a bit of prototyping there but not quite ready to release anything yet.

**Comment by russhwolf** [comment]
I've added a JS implementation in 0.3. It's marked experimental because I haven't tested it as closely. Please try it out and give feedback!

**Comment by SimonSchubert** [comment]
The JS implementation works fine for me. Thanks for the work. I think it's save to close the issue.

**Comment by russhwolf** [comment]
Noted, thanks. In the back of my minds I've been leaving this open pending adding a JS version of the sample project, at which point I'd probably be comfortable removing the experimental marker and closing this issue.

**Comment by russhwolf** [comment]
JS Sample is now published. Will remove experimental marker and close this issue with the next release.
