### ISSUE TITLE
Use Dispatcher.IO instead of Dispatcher.Default by default

### ISSUE THREAD

**Issue by kirillzh** [russhwolf/multiplatform-settings#157]
Coroutines KMP now have Dispatcher.IO which seems more suitable as a default dispatcher for `SuspendSettings` and `FlowSettings`.

**Comment by vanniktech** [comment]
Is this a new thing since 1.7? Is it also available on native / ios?

**Comment by kirillzh** [comment]
> Is this a new thing since 1.7? Is it also available on native / ios?

Yup, was added in 1.7 https://github.com/Kotlin/kotlinx.coroutines/pull/3576

**Comment by russhwolf** [comment]
Sorry to leave this sitting, but yes this makes sense (and better to do now while the coroutine APIs are still experimental). Feel free to open a PR, or I'll get to it at some point over the next few weeks (overdue for a 1.9 update anyway)

**Comment by russhwolf** [comment]
This was added in version 1.1.0
