### ISSUE TITLE
ERROR ReferenceError: localStorage is not defined on Web Extension

### ISSUE THREAD

**Issue by ar-g** [russhwolf/multiplatform-settings#165]
I'm currently getting:

```
ERROR ReferenceError: localStorage is not defined
    at new StorageSettings (MultiplatformSettings-multiplatform-settings.js:61:1)
    at new LocalStorageSettings (common-store.js:273:1)
```

When trying to initialise Settings in web-extension:
```
StorageSettings()
```

Is there a specific place I should be trying to do it?

**Comment by ar-g** [comment]
made some progress with this interface:
```
public external interface ChromeStorage {
    fun set(items: dynamic): Promise<Unit>
    fun get(key: String): Promise<dynamic>
    fun remove(key: String): Promise<Unit>
    fun clear(): Promise<Unit>
}
```
 which is doesn't really fit synchronous interface of Settings, so I'd probably have to throw away the library and roll different implementations with suspend as part of the interface

**Comment by russhwolf** [comment]
You might be able to get it working with the `SuspendSettings` interface in the coroutines module.

**Comment by russhwolf** [comment]
@ar-g Do you still need help here? I'm inclined to close this unless you think there's something the library could add that would help your use-case.

**Comment by russhwolf** [comment]
@aggarwalpulkit596 The library is not doing anything explicitly to help you with web worker. But if you have a `Promise`-based interface like the `ChromeStorage` defined above, you should be able to convert the promises to suspend functions and use that to write a custom implementation of `SuspendSettings`.
