### ISSUE TITLE
Suggestion: Translate README.md to Korean

### ISSUE THREAD

**Issue by wooram-yang** [russhwolf/multiplatform-settings#183]
Hi, I wanna translate the README.md into Korean. 
Do you mind if I do that?

**Comment by russhwolf** [comment]
Sorry that I didn't notice this initially. Since I don't know Korean myself, I'm hesitant to maintain an official Korean translation that I won't be able to update easily. But if you'd like to translate and host it elsewhere, I'd be happy to add a link from the official documentation.

**Comment by wooram-yang** [comment]
Thanks for your reply! I see. Let me write a PR.
