### ISSUE TITLE
Incompatible with Koin on JS test

### ISSUE THREAD

**Issue by danidiprana** [russhwolf/multiplatform-settings#185]
**Reproducible**
Yes

**Step to reproduce**
1. Have an integration test running on JS.
1. Add dependency `multiplatform-settings` or `multiplatform-settings-coroutines` or `multiplatform-settings-no-arg`
1. Run the integration test running on JS.
2. Observe. The test fails even though there is no implementation from multiplatform-settings (only add the dependency)

Error message
```
IllegalStateException: KoinApplication has not been started
IllegalStateException: KoinApplication has not been started
	at GlobalContext.protoOf.get_26vq(/Users/arno/workspace/koin-projects/koin/core/koin-core/src/jsMain/kotlin/org/koin/core/context/GlobalContext.kt:80)
	at Component.getKoin_18vqwx(/Users/arno/workspace/koin-projects/koin/core/koin-core/src/commonMain/kotlin/org/koin/core/component/KoinComponent.kt:33)
	at <global>.<unknown>(/Users/arno/workspace/koin-projects/koin/core/koin-core/src/commonMain/kotlin/org/koin/core/Koin.kt:35)
	at UnsafeLazyImpl.protoOf.get_value_j01efc(/Users/vidio/Workspace/vidio-app/shared/build/compileSync/js/test/testDevelopmentExecutable/kotlin/src/kotlin/util/Lazy.kt:81)
```

It's interesting since the test fails after we add the dependency and there is no implementation of multiplatform-settings in the project.

It seems like racing condition but I'm not sure what is the root cause since we only add the dependency.

Any idea?

**Comment by russhwolf** [comment]
Can you be more specific about what you mean by integration test? As-is, I don't understand how to recreate this issue. If you can post a sample project, it would help.

**Comment by danidiprana** [comment]
By that I mean there is testing using an staging environment to fetch the API and assert the result.

Sure, I'll try to recreate this issue on the sample project. In the meantime, I'm just wondering iss there any classes that run immediately when you compile or build the application without importing any implementation?

**Comment by russhwolf** [comment]
Multiplatform Settings generally doesn't do anything at startup. The only exception is the no-arg module on Android, which runs some setup code via androidx.startup, but that won't be relevant to JS. 

Your error is being thrown from Koin, so I would suggest checking if you're missing something in your Koin initialization in your integration test setup.

**Comment by danidiprana** [comment]
Interesting. The only confusion is the JS test fails only when I add the multiplatform-settings dependency. If I remove the dependency then the test will be green.

Sure, I'll check out Koin Initialization and I'll come back with a sample project.

**Comment by danidiprana** [comment]
Hello @russhwolf , turns out the root cause is the transitive dependency. I use `multipaltform-settings 1.1.1` which uses kotlin 1.9.20.

Thank you for your kind reply.
