### ISSUE TITLE
Cache control for multiplatform settings

### ISSUE THREAD

**Issue by danidiprana** [russhwolf/multiplatform-settings#190]
Hello,

is there an ability or possibility in the roadmap to automatically delete/purge a setting when the size is larger than something or if the value is inactive after a while? or maybe delete old data like the LRU algorithm?

thanks

**Comment by russhwolf** [comment]
I don't currently see this as in-scope for the library. None of the platform APIs we wrap currently provide this functionality, as far as I'm aware.
