### ISSUE TITLE
Library with Kotlin 2.0

### ISSUE THREAD

**Issue by TarasovVP** [russhwolf/multiplatform-settings#197]
After updating the Kotlin version to 2.0 in the KMP project in the commonMain module, the ability to import Settings disappeared.
After searching for the reason, I discovered that different versions of Kotlin load different sets of libraries.
Kotlin 1.9.20
<img width="494" alt="Снимок экрана 2024-06-24 в 20 28 56" src="https://github.com/russhwolf/multiplatform-settings/assets/34417782/c212a23d-2f48-4c78-b0c4-6fc4659867ea">
Kotlin 2.0.0
<img width="491" alt="Снимок экрана 2024-06-24 в 20 28 14" src="https://github.com/russhwolf/multiplatform-settings/assets/34417782/0ef833ab-32b4-48df-bafe-42009212ea9b">
The version for the commonMain module is missing

**Comment by russhwolf** [comment]
I'm unclear what the issue is here, as I have had no trouble using version 1.1.1 of the library from Kotlin 2.0 projects.

Nevertheless, version 1.2.0 is now released and built with Kotlin 2.0.
