### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#21]
Investigate and configure some form of continuous integration, to ease the process of reviewing changes.

Open to suggestions here. Otherwise I'll likely look into Travis or TeamCity first. 

Goal is to be able to run all tests on all platforms for both library and sample app, and ideally also run a linter.

**Comment by arkivanov** [comment]
We have full setup with Travis CI for our [Reaktive](https://github.com/badoo/Reaktive) library, including automatic publications of the new releases to Bintray. Here is our [article](https://translate.google.com/translate?sl=ru&tl=en&u=https%3A%2F%2Fm.habr.com%2Fru%2Fcompany%2Fbadoo%2Fblog%2F468841%2F) by @CherryPerry about it (auto-translate from Russian), we will publish a professional translation on Meduim soon. Stay tuned!

**Comment by russhwolf** [comment]
Ended up going with Azure after talking to @benasher44. Have this working now for builds/tests to all platforms but haven't added publishing yet, so going to leave this ticket open a little while longer.

**Comment by arkivanov** [comment]
We switched to GitHub Actions, just in case. 4x faster than Travis, not sure about Azure.

**Comment by benasher44** [comment]
I want to try Github actions. The nice thing about Azure is that it has first class gradle support: you can specify your CI in terms of gradle tasks, which is great if you're unfamiliar with the tooling/shell on a particular OS (Windows). Glad it worked out for ya!

**Comment by russhwolf** [comment]
Just released v0.5 which was built entirely via Azure Pipelines. Closing this but will keep an eye on Actions if it seems worth migrating to in the future.
