### ISSUE TITLE
FlowSettings in WasmJS

### ISSUE THREAD

**Issue by msusman1** [russhwolf/multiplatform-settings#212]
`toFlowSettings()` is not being resolved, is it possible to have `FlowSettings` instance for `Wasmjs` platform
```
@OptIn(ExperimentalSettingsApi::class)
actual fun createSetting(): FlowSettings {
    val delegate = localStorage
    val settings = StorageSettings(delegate)
    return settings.toFlowSettings()
}
```

**Comment by russhwolf** [comment]
`toFlowSettings()` is only available for implementations that are observable (ie `ObservableSettings`, not just `Settings`). One option is to add the `multiplatform-settings-make-observable` module and do `settings.makeObservable().toFlowSettings()`. But note the limitation that you will only receive updates from changes made to the same instance.
