### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#22]
Improve publishing configuration to automate publication to Maven Central. This way consumers wouldn't need to add a one-time-use Bintray dependency.

**Comment by romanandreyvich** [comment]
Any progress here? This issue blocks us because we want to use the library and at the same time we want to use kotlin.cocoapods plugin. But for now this is impossible because of problem described here https://github.com/JetBrains/kotlin-native/issues/3208#issuecomment-514581098

**Comment by romanandreyvich** [comment]
Also the solution https://github.com/JetBrains/kotlin-native/issues/3208#issuecomment-514599882 doesn't work for us

**Comment by russhwolf** [comment]
No progress because I haven't been prioritising this. Will try to look into it soon. (Also I realized that [package search](https://package-search.jetbrains.com/) only indexes maven central and I would love to be on there)

That said, I don't understand how deploying this library to maven central instead of jcenter impacts your use of cocoapods.

**Comment by russhwolf** [comment]
Ok publishing configuration is the worst but version 0.6 is now deployed to Maven Central! Try it out and let me know if anything went wrong that I missed. Deploy for 0.6-1.4-M2 is in progress, but otherwise I don't plan to go back and redeploy any other versions.

Not currently planning to do regular snapshot builds but if anyone would like that to happen, open a new ticket and I'll consider it.
