### ISSUE TITLE
Latest versions are not available to download from here https://dl.bintray.com/russhwolf/multiplatform-settings/com/russhwolf/multiplatform-settings-common/

### ISSUE THREAD

**Issue by jittya** [russhwolf/multiplatform-settings#26]
Latest versions are not available in Maven repository. https://dl.bintray.com/russhwolf/multiplatform-settings/com/russhwolf/multiplatform-settings-common/

**Comment by russhwolf** [comment]
Starting in 0.2 the dependency format changed since the library is now built with the `kotlin-multiplatform` gradle plugin. The common dependency is now titled [metadata](https://dl.bintray.com/russhwolf/multiplatform-settings/com/russhwolf/multiplatform-settings-metadata/).

**Comment by jittya** [comment]
Sorry. I was using latest InteliJ Community Edition. When i opened my project in Android Studio dependencies are downloaded.
