### ISSUE TITLE
Update to Kotlin 1.3.40

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#28]
Currently blocked by [KT-31917](https://youtrack.jetbrains.com/issue/KT-31917) (JS) and [KT-32170](https://youtrack.jetbrains.com/issue/KT-32170) (Native) which are both compile-time failures that occur when test code depends on a separate gradle module. Need to either restructure tests to not depend on separate `tests` module or wait for these issues to be fixed.

**Comment by russhwolf** [comment]
Turns out, adjusting the config to use `kotlin.srcDir` to include shared tests instead of a `tests` gradle module was pretty straightforward. 1.3.40 is now published to bintray.

**Comment by kuhnroyal** [comment]
I am running into KT-32170 as soon as I add this library to `commonMain` sources.
Any suggestions?
