### ISSUE TITLE
Call for use-cases: Non-persisted settings

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#48]
The discussion in #47 raised the idea of having non-persisted, in-memory Settings instances outside the context of tests/mocks. Since this functionality already exists in `MockSettings`, I'd like to get more feedback around what other use-cases exist. That way we can come up with a more generic name that fits all use-cases better.

**Comment by russhwolf** [comment]
Not planning any changes here in the immediate future, but I wanted to note one other use-case I've come across. A map-based settings instance like the current `MockSettings` coupled with some sort of "save-to-disk" lambda that runs on put/remove/clear operations might be a nice way to support custom platforms more easily.

**Comment by arkivanov** [comment]
I got a use case. I need to disable persistence in some circumstance. At the moment in such cases, I'm passing `null` `Settings.Factory`, and so I have write two variants of using classes: persistent and in-memory. Having in-memory settings would safe a lot of boilerplate, I would just pass in-memory `Settings.Factory` and that's it.

**Comment by russhwolf** [comment]
I'm going to close this in favor of #77 which will include this rename
