### ISSUE TITLE
no-arg version: function 'invoke()' is not found

### ISSUE THREAD

**Issue by dbaroncelli** [russhwolf/multiplatform-settings#56]
[I]([url]([url](url))) included:
`implementation("com.russhwolf:multiplatform-settings-no-arg:0.6")`
in CommonMain

but when I try to instantiate Settings, it gives me the error:
`Expression 'Settings' of type 'Settings.Companion' cannot be invoked as a function. The function 'invoke()' is not found`

**Comment by russhwolf** [comment]
I think I gave you the wrong import on Slack. Add `import com.russhwolf.settings.invoke`

You'll also probably want to use version `0.6-1.4.0-rc` instead of `0.6` to make sure the native side is compatible.

**Comment by dbaroncelli** [comment]
yes, it works now

it's strange that it's needed to write that import manually

isn't it possible to make the import automatic?

**Comment by russhwolf** [comment]
In version 0.6.3, I've deprecated `Settions.Companion.invoke()` in favor of a top-level `Settings()` function. It should have the same caller syntax but import better in the IDE.
