### ISSUE TITLE
Update no-arg module to use androidx.startup on Android

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#57]
The Android implementation of no-arg makes use of a content-provider internally to supply application context. There's now an AndroidX library so that libraries can share a single context instead of each needing to create their own provider. Is it worth migrating to now even though it's still in alpha? Leaning yes because KMP is full of experimental stuff anyway

**Comment by russhwolf** [comment]
Fixed in 0.6.3

**Comment by jeremangnr** [comment]
Hi @russhwolf ! Yesterday I was having a conversation with some folks from work about this, the question came up if using this mechanism creates a new context or uses the one from the app it's embedded in. What you say here suggests it would use the one from the app its embedded in, is that right?

**Comment by russhwolf** [comment]
It's a pretty small library so it's not too daunting to poke through the source if you want to understand it better. The entry point is a [content provider](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:startup/startup-runtime/src/main/java/androidx/startup/InitializationProvider.java;l=42) in the pattern first [popularized by Firebase](https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html) a few years back. It takes that ContentProvider context and calls `getApplicationContext()` when instantiating its [AppInitializer](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:startup/startup-runtime/src/main/java/androidx/startup/AppInitializer.java;l=71) class

**Comment by jeremangnr** [comment]
Thank you! I did go through the source, but I'm very new to Android development so it was kinda hard to figure out what was happening. This made it crystal clear :)
