### ISSUE TITLE
Apple Keychain implementation

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#59]
A couple people have asked about adding a keychain-backed `Settings` implementation. This seems worthwhile but I don't know those APIs well. Contributions welcome, whether it's helpful documentation, a reference implementation, or a PR.

**Comment by nbourdin** [comment]
Hello,
I found this library with an keychain implementation :
[https://github.com/Liftric/KVault](https://github.com/Liftric/KVault)

**Comment by russhwolf** [comment]
I've made some good progress here and plan to release a version of this soon as part of 0.7

**Comment by russhwolf** [comment]
This has been released in 0.7
