### ISSUE TITLE
Add API for reading the whole entry-set

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#6]
This would look something like
```
// android
fun entries(): Map<String, Any> = delegate.all

// ios
fun entries(): Map<String, Any> = delegate.dictionaryRepresentation()
```

The difficulty here is that this exposes platform-specific implementation details, such as storing `Int`s as `Long`s on iOS and `Double`s as `Long`s on Android.

**Comment by russhwolf** [comment]
I'm increasingly uninterested in providing this API due to the issue of exposing internals of how data is stored. Would love to hear if anyone has a strong need for it.

**Comment by vanniktech** [comment]
I don't
