### ISSUE TITLE
Add option to use commit() instead of apply() on Android

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#60]
The Android `SharedPreferences` interface has two methods to commit changes when editing. `apply()` is the recommended default and is what `AndroidSettings` does currently, but some users might prefer the synchronous `commit()` instead. I'd like to verify that there is demand for this, and if so add a configuration option to use `commit()` instead. Probably this is a constructor argument, but other suggestions are welcome.

**Comment by vanniktech** [comment]
I'm fine with `apply()` no need for commit

**Comment by anuragdalia** [comment]
how about something like a simple
`commit(async = true)`

**Comment by russhwolf** [comment]
Currently there's no common editor abstraction since Android is the only platform for which that exists. So there's nowhere to put a call like `commit(async = true)`.

**Comment by dzolnai** [comment]
This is a feature we would like to have, we use the Settings object to set the environment in our apps, and then immediately restart the app using ProcessPhoenix. Because `apply()` is used, and the process is killed, the changes are not saved.

**Comment by russhwolf** [comment]
Thanks for confirming a use-case. I'll merge the PR and look at doing a release this weekend.

**Comment by russhwolf** [comment]
Published 0.6.3 including this update
