### ISSUE TITLE
IDE cannot find the library when "kotlin.mpp.enableGranularSourceSetsMetadata=true"

### ISSUE THREAD

**Issue by dbaroncelli** [russhwolf/multiplatform-settings#62]
I am using Android Studio Canary 8

I enabled this line:
```
# Enable the hierarchy structure support
kotlin.mpp.enableGranularSourceSetsMetadata=true
```

on `gradle.properties`

as suggested here:
https://kotlinlang.org/docs/reference/migrating-multiplatform-project-to-14.html#migrate-to-the-hierarchical-project-structure

> In future versions, the hierarchical project structure with the usage of platform-dependent libraries in shared source sets will be the default in multiplatform projects. So the sooner you support it, the sooner users will be able to migrate. We'll also be very grateful if you report any bugs you find to our issue tracker.

but the IDE does not find the class, even thought it seems to compile:

<img width="815" alt="Schermata 2020-08-28 alle 23 03 17" src="https://user-images.githubusercontent.com/5320104/91618044-ad916600-e989-11ea-94a1-4f4902568c64.png">

not sure if it's a problem with the IDE, or with the gradle setting, or with the library itself.

Please note, I am using the no-arg library (no sure if it affects that in any way):

<img width="875" alt="Schermata 2020-08-28 alle 22 46 30" src="https://user-images.githubusercontent.com/5320104/91620095-44acec80-e98f-11ea-8e25-e5ba46ddc6f9.png">

**Comment by dbaroncelli** [comment]
With Android Studio Canary 10 and Kotlin 1.4.10 I don't seem to verify this anymore

**Comment by Ornolfr** [comment]
Having a similar issue with "no-arg" version of the library on AS 4.1 RC 3 with the newest KMP plugin. Code completion stops working for the whole shared module.

**Comment by russhwolf** [comment]
I've been trying to do some minimal samples to get a better understanding of the different HMPP flags, but I've been having trouble getting consistent behavior. Will keep investigating because I want to understand this better. If anyone has a simple project they can upload that exhibits the issue, please let me know.

**Comment by russhwolf** [comment]
In 0.7 I removed the hmpp flag from the library. I'm curious if that helps this issue.

**Comment by russhwolf** [comment]
All the hmpp stuff should now be working in 0.8.
