### ISSUE TITLE
Crypto abstraction

### ISSUE THREAD

**Issue by vanniktech** [russhwolf/multiplatform-settings#63]
It would be very nice if I could get a free crytpo abstraction where settings are encrypted for free.
Ideally, without changing the Settings API (put, get + remove).

My main targets are Android + iOS.

**Comment by russhwolf** [comment]
On Android you can already use [EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences). On iOS I'd like to add a keychain implementation (#59). Contributions welcome for that or any other platform

**Comment by vanniktech** [comment]
Oh that's neat. If anyone is interested in an `EncryptedSettingsFactory`:

```kotlin
class EncryptedSettingsFactory(private val context: Context) : Settings.Factory {
  private val masterKey = MasterKey.Builder(context)
    .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
    .setUserAuthenticationRequired(false)
    .build()

  override fun create(name: String?): Settings {
    val preferencesName = name ?: "${context.packageName}_preferences"

    return AndroidSettings(EncryptedSharedPreferences.create(
      context,
      preferencesName,
      masterKey,
      AES256_SIV,
      AES256_GCM
    ))
  }
}
```

**Comment by jeffnyauke** [comment]
How can we do this for iOS

**Comment by russhwolf** [comment]
You can use `KeychainSettings` on iOS. Make sure to update to version 0.7.2 to avoid #79
