### ISSUE TITLE
Rename Settings implementations

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#77]
Now that some platforms have multiple `Settings` implementations, it's confusing that one of them might be named for the platforms and others aren't. For consistency, I plan to rename things so all implementations are named for the API they delegate to. For instance,
`AndroidSettings` -> `SharedPreferencesSettings`
`AppleSettings` -> `NSUserDefaultsSettings` (or `UserDefaultsSettings`, I'm undecided here)
`JvmPreferencesSettings` -> `PreferencesSettings`
`JvmPropertiesSettings` -> `PropertiesSettings`

Might also be a nice time to tackle renaming `MockSettings`, per #48

An alternative would be to move everything to the naming convention that the JVM implementations use currently, which includes the platform and the delegating API. But I think that may be too verbose and feels a little redundant in retrospect.

**Comment by vanniktech** [comment]
I'd go for UserDefaultsSettings.

As for `MockSettings` -> `InMemorySettings`?

**Comment by russhwolf** [comment]
I'm planning to do this soon ahead of a 1.0 release. I'll plan to include deprecated typaliases to aid migration but this will be a breaking change.

**Comment by russhwolf** [comment]
This was done in `1.0.0-alpha01`. I opted to stick with `NSUserDefaultsSettings` over `UserDefaultsSettings` in order to prioritize consistency in the Kotlin naming convention over consistency in Swift-side usage.

**Comment by vanniktech** [comment]
I'm already on alpha01 but for others, the changlog entry: 

`-BREAKING: Rename Settings implementations to be based on the underlying API used rather than the platform`

is *good*. Would be nice if there was a list though like it used to be called XY and now it's XYZ. I had to look up the new names in this repository.

**Comment by russhwolf** [comment]
Good point. I added the list to the changelog. (It's also in a blog post I'm currently preparing as I update all these tickets). And there are deprecated typealiases to the old names in 1.0.0-alpha01 to help with the migration, though I plan to remove those for the final 1.0 release.
