### ISSUE TITLE
Remove default values for defaultValue arguments

### ISSUE THREAD

**Issue by russhwolf** [russhwolf/multiplatform-settings#78]
Currently, get-oriented APIs in the library take the form
```kotlin
getInt(key: String, defaultValue: Int = 0): Int
getIntOrNull(key: String): Int?
```
In almost every case where there's a `defaultValue` argument to make a getter non-nullable, a default value is provided for that argument. This lets you do things like
```kotlin
val a: Int = getInt("key")
```
which implicitly returns `0` if `"key"` is not present. In retrospect, this seems like it's probably not frequently a desired behavior. More intuitive might be something like
```kotlin
getInt(key: String, defaultValue: Int): Int
getInt(key: String): Int?
```
This is the style that [Multiplatform-Preferences](https://github.com/florent37/Multiplatform-Preferences) uses, for instance. This way you always have the same function name, and nullability is controlled by whether a default value is provided.

I'm considering refactoring toward that second style. However it could be awkward to do that in a way that respects existing users if they depend on the default value of the `defaultValue` argument. So I'd like to get a sense of whether this would be problematic for people.

There's also a less impactful option, where the `getIntOrNull()`-style functions stay unchanged and just the default values are removed from the existing `getInt()`-style functions.
```kotlin
getInt(key: String, defaultValue: Int): Int
getIntOrNull(key: String): Int?
```
In any event, I want to get a sense of current usage and what impact this might have on consumers.

**Comment by vanniktech** [comment]
I like the current API.

**Comment by russhwolf** [comment]
I'm planning to implement the last option--removing default values for `defaultValue` parameters--ahead of a 1.0 release. I think it will be possible to avoid it being a breaking change by using @Deprecated annotations, though I'll probably drop the deprecated functions in the final 1.0 release itself

**Comment by russhwolf** [comment]
This was done in `1.0.0-alpha01`
