### ISSUE TITLE
Issue consuming from multiplatform module(iOS)

### ISSUE THREAD

**Issue by fullkomnun** [russhwolf/multiplatform-settings#8]
Hi, nice library :)

I'm trying to depend on the kotlin-multiplatform-settings from within a kotlin multi-platform library.
The iOS target depends on the correponding iOS dependency: 
implementation "com.russhwolf:multiplatform-settings-ios:0.1".

When trying to build this module, I get the following error:
Could not resolve all files for configuration ':common-client:iOSCompileKlibraries'.
> Could not resolve com.russhwolf:multiplatform-settings-ios:0.1.
  Required by:
      project :common-client
   > Unable to find a matching configuration of com.russhwolf:multiplatform-settings-ios:0.1:
       - Configuration 'debugIos_arm64Link':
           - Found org.gradle.native.debuggable 'true' but wasn't required.
           - Found org.gradle.native.kotlin.platform 'ios_arm64' but wasn't required.
           - Found org.gradle.native.optimized 'false' but wasn't required.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-api' and found incompatible value 'kotlin-native-klib'.
           - Required org.jetbrains.kotlin.native.target 'ios_arm64' but no value provided.
           - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
       - Configuration 'debugIos_x64Link':
           - Found org.gradle.native.debuggable 'true' but wasn't required.
           - Found org.gradle.native.kotlin.platform 'ios_x64' but wasn't required.
           - Found org.gradle.native.optimized 'false' but wasn't required.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-api' and found incompatible value 'kotlin-native-klib'.
           - Required org.jetbrains.kotlin.native.target 'ios_arm64' but no value provided.
           - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
       - Configuration 'releaseIos_arm64Link':
           - Found org.gradle.native.debuggable 'false' but wasn't required.
           - Found org.gradle.native.kotlin.platform 'ios_arm64' but wasn't required.
           - Found org.gradle.native.optimized 'true' but wasn't required.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-api' and found incompatible value 'kotlin-native-klib'.
           - Required org.jetbrains.kotlin.native.target 'ios_arm64' but no value provided.
           - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
       - Configuration 'releaseIos_x64Link':
           - Found org.gradle.native.debuggable 'false' but wasn't required.
           - Found org.gradle.native.kotlin.platform 'ios_x64' but wasn't required.
           - Found org.gradle.native.optimized 'true' but wasn't required.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-api' and found incompatible value 'kotlin-native-klib'.
           - Required org.jetbrains.kotlin.native.target 'ios_arm64' but no value provided.
           - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.

Any ideas?

**Comment by fullkomnun** [comment]
Upgrading to 0.1.1 solved it.

**Comment by AlexeyKorshun** [comment]
I have this issue with 0.1.1 version. I fetch sample and can't build it.
