### ISSUE TITLE
Failed to resolve: multiplatform-settings-no-arg-android-0.7.6-samplessources

### ISSUE THREAD

**Issue by moeindev** [russhwolf/multiplatform-settings#86]
I'm having this issue when I add my kmm library as a dependency to my android project

**Comment by russhwolf** [comment]
It's impossible to say what's going on without more information. Can you link to your project or a sample that reproduces the issue? Failing that, it would help to at least see your gradle files.

**Comment by moeindev** [comment]
Update: after some digging, I solved my library's problem, and this samplesources seems like to be a bug! see here: https://youtrack.jetbrains.com/issue/KTIJ-10769

**Comment by russhwolf** [comment]
Ah, good to know!
