### ISSUE TITLE
Preferences are not persisting after app close

### ISSUE THREAD

**Issue by sdzshn3** [russhwolf/multiplatform-settings#89]
Preferences are saving in storage.. After clearing app from recents, preferences are getting vanished.
Info, using Android 11, and using this library in KMM

**Comment by russhwolf** [comment]
Is it possible you're running into the same issue as [here](https://github.com/russhwolf/multiplatform-settings/issues/52#issuecomment-716464191)?

**Comment by sdzshn3** [comment]
Did a stupid mistake.. Was calling .clear() instead of calling .remove(). Earlier there was only one preference, so I used .clear() after adding more preferences, forget to remove only one preference...
