### ISSUE TITLE
[Feature Request] Any chance of integrating iCloud Keychain?

### ISSUE THREAD

**Issue by jpteruel095** [russhwolf/multiplatform-settings#91]
Keychain is available using **KeychainSettings**. But I've looked up upon the source code, and it doesn't seem to have a customizability of allowing the user to enable iCloud synchronization. I can't see any instance of ** kSecAttrSynchronizable** in the whole source code.

I hope it does get implemented soon. Thank you.

**Comment by russhwolf** [comment]
There's a constructor that takes arbitrary key-value pairs if you want to do something non-default. I've never tried, but something like this should work.
```kotlin
val settings = KeychainSettings(
    kSecAttrService to CFBridgingRetain(name),
    kSecAttrSynchronizable to kCFBooleanTrue
)
```
`name` is whatever string you were passing to the other constructor, or you could omit that line if you don't want to pass a service name

**Comment by russhwolf** [comment]
I'm pretty sure there's nothing to do here, so I'm closing this. Feel free to reopen, or start a discussion, if you're still having trouble.
