### ISSUE TITLE
Support for apple silicon seems to be broken

### ISSUE THREAD

**Issue by micHar** [russhwolf/multiplatform-settings#96]
The 0.8 is supposed to work with new apple silicon targets but it doesn't work for me at least for `iosSimulatorArm64` target. Gradle sync doesn't seem to complain for the main artifact, but it complains for: `multiplatform-settings-no-arg`, `multiplatform-settings-coroutines-native-mt` (which makes sense because it uses coroutines 1.5.1 and support for apple silicon is added at 1.5.2 afaik). Also I don't use this feature but I think the `kotlinx.serialization` used is 1.2.2 which also isn't compatible with apple silicon (1.3.0-RC is).

**Comment by russhwolf** [comment]
Thanks for reporting. The missing targets in no-arg is an oversight. The missing coroutines and serialization targets are because I haven't republished since those libraries updated. I'll plan to republish soon with these targets added.

**Comment by russhwolf** [comment]
Fixed in 0.8.1
